name: Run Buildifier
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  run-buildifier:
    name: suggester / buildifier
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd $(mktemp -d)
          GO111MODULE=on go get github.com/bazelbuild/buildtools/buildifier@3.2.0
      - name: Run buildifier
        shell: bash
        run: |
          buildifier -mode=fix $(find . -name 'BUILD*' -o -name 'WORKSPACE*' -o -name '*.bzl' -type f)
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: buildifier

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write
